### PR TITLE
upgrade_deriv-api_depended_modules

### PR DESCRIPTION
**Pull request by ramin-fs**
https://redmine.deriv.cloud/issues/41004#upgrade_deriv-api_depended_modules

### CODE REVIEW

**Comment by shantanu-deriv** [comment]
If there are changes in package-lock, why is there no change in package.json?

**Review by shantanu-deriv — APPROVED** [review]

**Comment by ramin-fs** [comment]
> If there are changes in package-lock, why is there no change in package.json?

@shantanu-deriv consider a situation like this a-package@^6.7.* if we update our packages the package.json file will not change at all but package-lock.json will change.
In this case, one of the npm scripts updated the package-lock automatically and it works.

**Comment by chylli-binary** [comment]
> > If there are changes in package-lock, why is there no change in package.json?
> 
> @shantanu-deriv consider a situation like this a-package@^6.7.* if we update our packages the package.json file will not change at all but package-lock.json will change.
> In this case, one of the npm scripts updated the package-lock automatically and it works.

I think you are talking about the patch version. but we need to upgrade minor version even major version also. Please see my version : https://github.com/binary-com/deriv-api/pull/62/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R38

I used this command `npm i -g npm-check-updates && ncu -u && npm i`

**Comment by ramin-fs** [comment]
> > > If there are changes in package-lock, why is there no change in package.json?
> > 
> > 
> > @shantanu-deriv consider a situation like this a-package@^6.7.* if we update our packages the package.json file will not change at all but package-lock.json will change.
> > In this case, one of the npm scripts updated the package-lock automatically and it works.
> 
> I think you are talking about the patch version. but we need to upgrade minor version even major version also. Please see my version : https://github.com/binary-com/deriv-api/pull/62/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R38
> 
> I used this command `npm i -g npm-check-updates && ncu -u && npm i`

OK then, by the way, I only wanted to fix the a_simple_bot.js issue, I will merge my changes with yours. Do you think it's OK?

**Comment by chylli-binary** [comment]
> OK then, by the way, I only wanted to fix the a_simple_bot.js issue, I will merge my changes with yours. Do you think it's OK?

Sure. But I'm afraid after merging my change, then the problem appear again :)

**Pull request closed without merging**
